# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinemaAdmin',
            new_name='CinemaAdmins',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedules',
        ),
        migrations.RenameModel(
            old_name='Seatlock',
            new_name='Seatlocks',
        ),
    ]
