# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0002_auto_20190812_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_rowid', models.IntegerField()),
                ('seat_colid', models.IntegerField()),
                ('seat_ofhallid', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_userid',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_userphone',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_seat4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_seat5',
            field=models.IntegerField(null=True),
        ),
    ]
