# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0005_auto_20190821_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='seat_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
