# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0006_seats_seat_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlocks',
            name='lock_orderid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
