# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaAdmins',
            fields=[
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_password', models.CharField(max_length=128)),
                ('Admin_phone', models.CharField(max_length=20)),
                ('Admin_email', models.CharField(blank=True, max_length=100)),
                ('Admin_name', models.CharField(blank=True, max_length=60)),
                ('Admin_cinemaid', models.IntegerField(null=True)),
                ('Admin_type', models.IntegerField(choices=[(0, '超级管理员'), (1, '普通管理员')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('cinema_id', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_name', models.CharField(max_length=128)),
                ('cinema_addr', models.CharField(max_length=128)),
                ('cinema_phone', models.CharField(max_length=20)),
                ('cinema_photo', models.ImageField(blank=True, max_length=256, upload_to='')),
                ('cinema_isopen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=60)),
                ('hall_type', models.CharField(max_length=128)),
                ('hall_seatscount', models.IntegerField(null=True)),
                ('hall_cinemaid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_num', models.CharField(max_length=20)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('order_userphone', models.CharField(max_length=60, null=True)),
                ('order_skdid', models.IntegerField(null=True)),
                ('order_seat1', models.IntegerField(null=True)),
                ('order_seat2', models.IntegerField(null=True)),
                ('order_seat3', models.IntegerField(null=True)),
                ('order_seat4', models.IntegerField(null=True)),
                ('order_seat5', models.IntegerField(null=True)),
                ('order_prices', models.IntegerField(null=True)),
                ('order_status', models.IntegerField(choices=[(0, '未支付'), (1, '已取消'), (2, '已完成')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('skd_id', models.AutoField(primary_key=True, serialize=False)),
                ('skd_date', models.DateField(null=True)),
                ('skd_starttime', models.TimeField(null=True)),
                ('skd_endtime', models.TimeField(blank=True, null=True)),
                ('skd_hallid', models.IntegerField(null=True)),
                ('skd_filmid', models.IntegerField(null=True)),
                ('skd_language', models.CharField(max_length=20)),
                ('skd_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seatlocks',
            fields=[
                ('lock_id', models.AutoField(primary_key=True, serialize=False)),
                ('lock_skdid', models.IntegerField(null=True)),
                ('lock_orderid', models.IntegerField(null=True)),
                ('lock_seatnum', models.IntegerField(null=True)),
                ('lock_time', models.TimeField(auto_now_add=True)),
                ('lock_type', models.IntegerField(choices=[(0, '可选'), (1, '锁定未支付'), (2, '已支付')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_rowid', models.IntegerField()),
                ('seat_colid', models.IntegerField()),
                ('seat_ofhallid', models.IntegerField(null=True)),
            ],
        ),
    ]
