# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=20)),
                ('comment_filmid', models.IntegerField()),
                ('comment_content', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=128)),
                ('user_nickname', models.CharField(blank=True, max_length=60)),
                ('user_gender', models.IntegerField(choices=[(1, '保密'), (2, '男'), (3, '女')], default=1)),
                ('user_birthday', models.DateField(null=True)),
                ('user_signature', models.CharField(blank=True, max_length=200)),
                ('user_photo', models.ImageField(blank=True, max_length=256, upload_to='')),
                ('user_phone', models.CharField(max_length=20, unique=True)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_regtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
