# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
