# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cgy_id', models.AutoField(primary_key=True, serialize=False)),
                ('cgy_pid', models.IntegerField(default=0)),
                ('cgy_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FilmComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=20)),
                ('filmid', models.IntegerField()),
                ('comment_content', models.CharField(max_length=3000)),
                ('comment_userid', models.IntegerField(null=True)),
                ('comment_datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_likenum', models.IntegerField(default=0)),
                ('comment_isdel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='filmpf',
            fields=[
                ('filmpf_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_pf', models.IntegerField(blank=True, null=True)),
                ('daily_pf', models.IntegerField(blank=True, null=True)),
                ('film_rating', models.IntegerField(blank=True)),
                ('film_ratingcount', models.IntegerField(blank=True)),
                ('filmid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_namech', models.CharField(max_length=300)),
                ('film_releasdate', models.DateField(blank=True, null=True)),
                ('film_status', models.IntegerField(choices=[(0, '正在热映'), (1, '即将上映'), (2, '未上映')], default=2)),
                ('film_actor1', models.CharField(blank=True, max_length=60, null=True)),
                ('film_actor2', models.CharField(blank=True, max_length=60, null=True)),
                ('film_actor3', models.CharField(blank=True, max_length=60, null=True)),
                ('film_photo', models.CharField(blank=True, max_length=256, null=True)),
                ('film_director', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmsDetail',
            fields=[
                ('filmdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_nameen', models.CharField(blank=True, max_length=300, null=True)),
                ('film_intro', models.CharField(blank=True, max_length=3000, null=True)),
                ('film_type1', models.IntegerField(blank=True, choices=[(1, '爱情'), (2, '喜剧'), (3, '动画'), (4, '剧情'), (5, '恐怖'), (6, '惊悚'), (7, '科幻'), (8, '动作'), (9, '悬疑'), (10, '犯罪'), (11, '冒险'), (12, '战争'), (13, '奇幻'), (14, '运动'), (15, '家庭'), (16, '古装'), (17, '武侠'), (18, '西部'), (19, '历史'), (20, '传记'), (21, '歌舞'), (22, '黑色电影'), (23, '短片'), (24, '纪录片'), (25, '其他')], null=True)),
                ('film_type2', models.IntegerField(blank=True, choices=[(1, '爱情'), (2, '喜剧'), (3, '动画'), (4, '剧情'), (5, '恐怖'), (6, '惊悚'), (7, '科幻'), (8, '动作'), (9, '悬疑'), (10, '犯罪'), (11, '冒险'), (12, '战争'), (13, '奇幻'), (14, '运动'), (15, '家庭'), (16, '古装'), (17, '武侠'), (18, '西部'), (19, '历史'), (20, '传记'), (21, '歌舞'), (22, '黑色电影'), (23, '短片'), (24, '纪录片'), (25, '其他')], null=True)),
                ('film_type3', models.IntegerField(blank=True, choices=[(1, '爱情'), (2, '喜剧'), (3, '动画'), (4, '剧情'), (5, '恐怖'), (6, '惊悚'), (7, '科幻'), (8, '动作'), (9, '悬疑'), (10, '犯罪'), (11, '冒险'), (12, '战争'), (13, '奇幻'), (14, '运动'), (15, '家庭'), (16, '古装'), (17, '武侠'), (18, '西部'), (19, '历史'), (20, '传记'), (21, '歌舞'), (22, '黑色电影'), (23, '短片'), (24, '纪录片'), (25, '其他')], null=True)),
                ('film_type4', models.IntegerField(blank=True, choices=[(1, '爱情'), (2, '喜剧'), (3, '动画'), (4, '剧情'), (5, '恐怖'), (6, '惊悚'), (7, '科幻'), (8, '动作'), (9, '悬疑'), (10, '犯罪'), (11, '冒险'), (12, '战争'), (13, '奇幻'), (14, '运动'), (15, '家庭'), (16, '古装'), (17, '武侠'), (18, '西部'), (19, '历史'), (20, '传记'), (21, '歌舞'), (22, '黑色电影'), (23, '短片'), (24, '纪录片'), (25, '其他')], null=True)),
                ('film_duration', models.IntegerField(blank=True, null=True)),
                ('film_country', models.CharField(blank=True, max_length=200, null=True)),
                ('film_language1', models.CharField(blank=True, max_length=20, null=True)),
                ('film_language2', models.CharField(blank=True, max_length=20, null=True)),
                ('filmid', models.IntegerField(default=0)),
            ],
        ),
    ]
