# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_namech', models.CharField(max_length=300)),
                ('film_nameen', models.CharField(blank=True, max_length=300)),
                ('film_intro', models.CharField(max_length=3000)),
                ('film_type1', models.CharField(max_length=30)),
                ('film_type2', models.CharField(blank=True, max_length=30)),
                ('film_type3', models.CharField(blank=True, max_length=30)),
                ('film_type4', models.CharField(blank=True, max_length=30)),
                ('film_country', models.CharField(max_length=200)),
                ('film_language1', models.CharField(max_length=20)),
                ('film_language2', models.CharField(blank=True, max_length=20)),
                ('film_releasdate', models.DateField(blank=True)),
                ('film_status', models.IntegerField(choices=[(0, '正在热映'), (1, '即将上映'), (2, '未上映')])),
                ('film_actor1', models.CharField(blank=True, max_length=60)),
                ('film_actor2', models.CharField(blank=True, max_length=60)),
                ('film_actor3', models.CharField(blank=True, max_length=60)),
                ('film_photo', models.CharField(max_length=256)),
                ('film_rating', models.IntegerField(blank=True)),
                ('film_ratingcount', models.IntegerField(blank=True)),
                ('film_diretor', models.CharField(max_length=60)),
            ],
        ),
    ]
