# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cgy_id', models.AutoField(primary_key=True, serialize=False)),
                ('cgy_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='filmpf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_rating', models.IntegerField(blank=True)),
                ('film_ratingcount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False)),
                ('film_namech', models.CharField(max_length=300)),
                ('film_releasdate', models.DateField(blank=True)),
                ('film_status', models.IntegerField(choices=[(0, '正在热映'), (1, '即将上映'), (2, '未上映')])),
                ('film_actor1', models.CharField(blank=True, max_length=60)),
                ('film_actor2', models.CharField(blank=True, max_length=60)),
                ('film_actor3', models.CharField(blank=True, max_length=60)),
                ('film_photo', models.CharField(max_length=256)),
                ('film_diretor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FilmsDetail',
            fields=[
                ('films_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Film.Films')),
                ('film_nameen', models.CharField(blank=True, max_length=300)),
                ('film_intro', models.CharField(blank=True, max_length=3000)),
                ('film_type1', models.CharField(max_length=30)),
                ('film_type2', models.CharField(blank=True, max_length=30)),
                ('film_type3', models.CharField(blank=True, max_length=30)),
                ('film_type4', models.CharField(blank=True, max_length=30)),
                ('film_country', models.CharField(max_length=200)),
                ('film_language1', models.CharField(max_length=20)),
                ('film_language2', models.CharField(blank=True, max_length=20)),
            ],
            bases=('Film.films',),
        ),
    ]
