# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='film_rating',
        ),
        migrations.AddField(
            model_name='filmpf',
            name='film_rating',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
