# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0002_auto_20190810_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpf',
            name='film_want',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='filmsdetail',
            name='film',
            field=models.OneToOneField(db_column='film_id', on_delete=django.db.models.deletion.CASCADE, related_name='filmdetail', to='Film.Films'),
        ),
    ]
