# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0003_auto_20190810_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpf',
            name='film_rating',
            field=models.FloatField(blank=True),
        ),
    ]
