# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0004_auto_20190810_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='film_photo',
            field=models.ImageField(blank=True, null=True, upload_to='filmphoto'),
        ),
    ]
