# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0005_auto_20190812_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpf',
            name='daily_pf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filmpf',
            name='total_pf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
